version: '3'
#updated it works
services:
  auth-service:
    build: ./backend
    container_name: auth-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - REDIS_HOST=redis
      - PORT=5000
      - SALT=10
      - JWT_SECRET='5123abc'
      - CLIENT_URL=http://frontend:5173 # Update to the frontend service name
      - REDIS_PORT=6379
      - MY_EMAIL=techsharma53@gmail.com
      - MY_PASSWORD=onvguabxigdeszyb
    depends_on:
      - mongo
      - redis
    networks:
      - backend-network

  todos-service:
    build: ./todo-service
    container_name: todos-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - REDIS_HOST=redis       
      - REDIS_PORT=6379
      - PORT=5001
      - JWT_SECRET=5123abc
      - CLIENT_URL=http://frontend:5173 # Update to the frontend service name
    depends_on:
      - mongo
      - redis
    networks:
      - backend-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "5003:5003"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5000
      - TODOS_SERVICE_URL=http://todos-service:5001
      - CLIENT_URL=https://frontend:5173 # Update to the frontend service name
    depends_on:
      - auth-service
      - todos-service
    networks:
      - backend-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_GATEWAY_URL=https://api-gateway:5003
      - VITE_API_AUTH_URL=https://auth-service:5000
      - VITE_API_TODOS_URL=https://todos-service:5001
    networks:
      - frontend-network
      - backend-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend-network

networks:
  backend-network:
  frontend-network:

volumes:
  mongo-data: