apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: sujalsharma/backend-auth-app:v1
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb+srv://sujalsharma151:LGlw6zPfACVYI6Eg@cluster0.n15ev.mongodb.net/"
        - name: REDIS_HOST
          value: 'redis'
        - name: REDIS_PORT
          value: "6379"
        - name: SALT
          value: '10'
        - name: PORT
          value: 5000     
        - name: JWT_SECRET   
          value: '5123abc'
        - name: MY_EMAIL   
          value: 'techsharma53@gmail.com'
        - name: MY_PASSWORD
          value: 'onvguabxigdeszyb'  
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: auth
