apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sujalsharma/frontend-auth-app
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_GATEWAY_URL
              value: "http://api-gateway:5003"
            - name: VITE_API_AUTH_URL
              value: "http://auth-service:5000"
            - name: VITE_API_TODOS_URL
              value: "http://todos-service:5001"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer
