apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
data:
  JWT_SECRET: NTYyMWEyYzM=   # base64 encoded '5123abc'
  MY_EMAIL: dGVjaHNoYXJtYTUzQGdtYWlsLmNvbQ==  # base64 encoded 'techsharma53@gmail.com'
  MY_PASSWORD: b25ncnVhYnhpZ2Rlc3p5Yg==  # base64 encoded 'onvguabxigdeszyb'
