apiVersion: autoscaling.x-k8s.io/v1beta1
kind: VerticalPodAutoscaler
metadata:
  name: redis-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: redis
  updatePolicy:
    updateMode: "Auto"
