
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: sujalsharma/frontend-auth-app
        imagePullPolicy: Always
        env:
          - name: VITE_API_GATEWAY_URL
            value: "http://api-gateway:5003"
          - name: VITE_API_AUTH_URL
            value: "http://34.134.90.22:5000"
          - name: VITE_API_TODOS_URL
            value: "http://todos-service:5001"
          - name: JWT_SECRET
            value: '5123abc'  
        ports:
        - containerPort: 5173
